import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "火锅",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/9.png" sizes="any" />
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto ">
<main className="p-6 border-b flex items-center justify-between bg-blue-500 rounded-bl-3xl rounded-br-3xl">
<Link className="text-2xl font-bold text-white" href={"/"}>Tech Interpretations</Link>
<Link className="bg-slate-100 grid place-items-center py-2 px-4 rounded-full font-bold shadow-md shadow-red-500" href={"/create"}>Add New</Link>
</main>
    <main className=" p-4 text-lg">{children}</main>
        </div>
        </body>
    </html>
  );
}
